export const NOTE_ARCHIVE = "NOTE_ARCHIVE";
export const NOTE_SELECT = "NOTE_SELECT";
export const NOTE_DESELECT = "NOTE_DESELECT";
export const NOTE_NEW = "NOTE_NEW";
export const NOTE_DELETE = "NOTE_DELETE";
export const NOTES_DELETE_FROM_FOLDER = "NOTES_DELETE_FROM_FOLDER";
export const NOTE_CHANGE = "NOTE_CHANGE";
export const NOTES_FETCH = "NOTES_FETCH";
export const NOTES_FETCH_ERROR = "NOTES_FETCH_ERROR";
export const NOTES_ADD = "NOTES_ADD";
export const NOTES_ON_SEARCH = 'NOTES_ON_SEARCH';
export const NOTE_REMOVE_ACTIVE = "NOTE_REMOVE_ACTIVE";

export const FOLDER_SELECT = "FOLDER_SELECT";
export const FOLDER_DESELECT = "FOLDER_DESELECT";
export const FOLDER_NEW = "FOLDER_NEW";
export const FOLDER_EDIT = "FOLDER_EDIT";
export const FOLDER_SAVE = "FOLDER_SAVE";
export const FOLDER_DELETE = "FOLDER_DELETE";

export const SEARCH = "SEARCH";
export const SEARCH_DOC_ENABLE = "SEARCH_DOC_ENABLE";
export const SEARCH_DOC_DISABLE = "SEARCH_DOC_DISABLE";
export const SEARCH_UPDATE_REPLACE = "SEARCH_UPDATE_REPLACE";
export const SEARCH_TOGGLE_REPLACE = "SEARCH_TOGGLE_REPLACE";

export const SEARCH_NOTES = "SEARCH_NOTES";
export const SEARCH_NOTES_RESET = "SEARCH_NOTES_RESET";

export const EDITOR_NEW = "EDITOR_NEW";
export const EDITOR_LOAD = "EDITOR_LOAD";
export const EDITOR_UPDATE = "EDITOR_UPDATE";
export const EDITOR_SEARCH = "EDITOR_SEARCH";
export const EDITOR_REPLACE = "EDITOR_REPLACE";
